require('dotenv').config();

const mongoose = require('mongoose');
const Book = require('./models/Book');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/booklog';

const books = [
  {
    title: '불편한 편의점',
    author: '김호연',
    category: '국내 소설',
    status: 'done',
    rating: 4.5,
    memo: '동네 편의점을 배경으로 따뜻한 인물들이 오래 남는다.',
    startDate: '2025-01-05',
    endDate: '2025-01-12',
  },
  {
    title: '아몬드',
    author: '손원평',
    category: '국내 소설',
    status: 'done',
    rating: 4,
    memo: '감정을 배우는 과정을 담담하게 따라가게 된다.',
    startDate: '2025-01-20',
    endDate: '2025-01-27',
  },
  {
    title: '82년생 김지영',
    author: '조남주',
    category: '국내 소설',
    status: 'paused',
    rating: 3.5,
    memo: '현실적인 장면이 많아 천천히 읽는 중.',
    startDate: '2025-02-02',
    endDate: '',
  },
  {
    title: '파친코',
    author: '이민진',
    category: '국내 소설',
    status: 'reading',
    rating: 4,
    memo: '세대를 건너는 가족 서사가 묵직하다.',
    startDate: '2025-02-10',
    endDate: '',
  },
  {
    title: '채식주의자',
    author: '한강',
    category: '국내 소설',
    status: 'want',
    rating: 0,
    memo: '문체와 상징을 집중해서 읽어보고 싶다.',
    startDate: '',
    endDate: '',
  },
  {
    title: '소년이 온다',
    author: '한강',
    category: '국내 소설',
    status: 'want',
    rating: 0,
    memo: '역사와 개인의 고통을 함께 생각하며 읽기.',
    startDate: '',
    endDate: '',
  },
  {
    title: '달러구트 꿈 백화점',
    author: '이미예',
    category: '국내 소설',
    status: 'done',
    rating: 4,
    memo: '가볍지만 상상력이 좋아 쉬는 날 읽기 좋았다.',
    startDate: '2025-03-01',
    endDate: '2025-03-04',
  },
  {
    title: '미드나잇 라이브러리',
    author: '매트 헤이그',
    category: '해외 소설',
    status: 'done',
    rating: 4,
    memo: '선택과 후회에 대해 부드럽게 질문한다.',
    startDate: '2025-03-12',
    endDate: '2025-03-18',
  },
  {
    title: '노르웨이의 숲',
    author: '무라카미 하루키',
    category: '해외 소설',
    status: 'reading',
    rating: 3.5,
    memo: '분위기가 강해서 조금씩 읽는 중.',
    startDate: '2025-03-21',
    endDate: '',
  },
  {
    title: '어린 왕자',
    author: '앙투안 드 생텍쥐페리',
    category: '해외 소설',
    status: 'done',
    rating: 5,
    memo: '짧지만 다시 읽을 때마다 다른 문장이 남는다.',
    startDate: '2025-04-01',
    endDate: '2025-04-02',
  },
  {
    title: '데미안',
    author: '헤르만 헤세',
    category: '해외 소설',
    status: 'want',
    rating: 0,
    memo: '성장소설의 고전으로 다시 읽어보기.',
    startDate: '',
    endDate: '',
  },
  {
    title: '연금술사',
    author: '파울로 코엘료',
    category: '해외 소설',
    status: 'done',
    rating: 4,
    memo: '단순한 문장 속에 계속 움직이게 하는 힘이 있다.',
    startDate: '2025-04-07',
    endDate: '2025-04-10',
  },
  {
    title: '오만과 편견',
    author: '제인 오스틴',
    category: '해외 소설',
    status: 'paused',
    rating: 3,
    memo: '인물 관계가 재미있지만 호흡을 맞추는 중.',
    startDate: '2025-04-15',
    endDate: '',
  },
  {
    title: '모순',
    author: '양귀자',
    category: '국내 소설',
    status: 'reading',
    rating: 4.5,
    memo: '문장마다 삶의 아이러니가 선명하다.',
    startDate: '2025-04-20',
    endDate: '',
  },
  {
    title: '여행의 이유',
    author: '김영하',
    category: '에세이',
    status: 'done',
    rating: 4,
    memo: '여행보다 이동하는 마음에 대한 책처럼 느껴졌다.',
    startDate: '2025-05-02',
    endDate: '2025-05-05',
  },
  {
    title: '나는 나로 살기로 했다',
    author: '김수현',
    category: '에세이',
    status: 'done',
    rating: 3.5,
    memo: '자기 돌봄에 대한 문장이 쉽게 읽힌다.',
    startDate: '2025-05-09',
    endDate: '2025-05-13',
  },
  {
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    category: '에세이',
    status: 'paused',
    rating: 3,
    memo: '솔직한 기록이라 컨디션이 좋을 때 이어서 읽기.',
    startDate: '2025-05-15',
    endDate: '',
  },
  {
    title: '그러라 그래',
    author: '양희은',
    category: '에세이',
    status: 'want',
    rating: 0,
    memo: '편안한 목소리의 글을 기대한다.',
    startDate: '',
    endDate: '',
  },
  {
    title: '언어의 온도',
    author: '이기주',
    category: '에세이',
    status: 'done',
    rating: 3.5,
    memo: '일상의 표현을 돌아보게 한다.',
    startDate: '2025-05-18',
    endDate: '2025-05-21',
  },
  {
    title: '하마터면 열심히 살 뻔했다',
    author: '하완',
    category: '에세이',
    status: 'reading',
    rating: 3.5,
    memo: '힘을 빼는 태도에 대해 생각하게 된다.',
    startDate: '2025-05-25',
    endDate: '',
  },
  {
    title: '아주 작은 습관의 힘',
    author: '제임스 클리어',
    category: '자기계발',
    status: 'done',
    rating: 5,
    memo: '습관을 작게 설계하는 방법이 바로 적용 가능하다.',
    startDate: '2025-06-01',
    endDate: '2025-06-08',
  },
  {
    title: '역행자',
    author: '자청',
    category: '자기계발',
    status: 'done',
    rating: 3.5,
    memo: '실행력을 강조하는 메시지가 강하다.',
    startDate: '2025-06-10',
    endDate: '2025-06-15',
  },
  {
    title: '원씽',
    author: '게리 켈러',
    category: '자기계발',
    status: 'reading',
    rating: 4,
    memo: '우선순위를 좁히는 연습을 해보는 중.',
    startDate: '2025-06-20',
    endDate: '',
  },
  {
    title: '그릿',
    author: '앤절라 더크워스',
    category: '자기계발',
    status: 'want',
    rating: 0,
    memo: '꾸준함을 과학적으로 설명한 부분이 궁금하다.',
    startDate: '',
    endDate: '',
  },
  {
    title: '타이탄의 도구들',
    author: '팀 페리스',
    category: '자기계발',
    status: 'paused',
    rating: 3,
    memo: '챕터별로 필요한 부분부터 읽는 중.',
    startDate: '2025-06-25',
    endDate: '',
  },
  {
    title: '데일 카네기 인간관계론',
    author: '데일 카네기',
    category: '자기계발',
    status: 'done',
    rating: 4,
    memo: '기본적인 관계 태도를 점검하기 좋다.',
    startDate: '2025-07-01',
    endDate: '2025-07-08',
  },
  {
    title: '부자 아빠 가난한 아빠',
    author: '로버트 기요사키',
    category: '경제경영',
    status: 'done',
    rating: 4,
    memo: '자산과 부채를 구분하는 관점이 인상적이다.',
    startDate: '2025-07-10',
    endDate: '2025-07-14',
  },
  {
    title: '돈의 속성',
    author: '김승호',
    category: '경제경영',
    status: 'reading',
    rating: 4,
    memo: '돈을 대하는 태도를 정리하며 읽는 중.',
    startDate: '2025-07-18',
    endDate: '',
  },
  {
    title: '트렌드 코리아 2025',
    author: '김난도 외',
    category: '경제경영',
    status: 'want',
    rating: 0,
    memo: '소비 트렌드 흐름을 훑어보기.',
    startDate: '',
    endDate: '',
  },
  {
    title: '주식투자 무작정 따라하기',
    author: '윤재수',
    category: '경제경영',
    status: 'paused',
    rating: 3,
    memo: '기초 개념 정리용으로 필요한 장만 보는 중.',
    startDate: '2025-07-22',
    endDate: '',
  },
  {
    title: '초격차',
    author: '권오현',
    category: '경제경영',
    status: 'done',
    rating: 4,
    memo: '조직과 리더십 관점에서 읽을 부분이 많았다.',
    startDate: '2025-08-01',
    endDate: '2025-08-06',
  },
  {
    title: '넛지',
    author: '리처드 탈러, 캐스 선스타인',
    category: '경제경영',
    status: 'reading',
    rating: 4,
    memo: '선택 설계라는 관점이 서비스 기획에도 유용하다.',
    startDate: '2025-08-10',
    endDate: '',
  },
  {
    title: '사피엔스',
    author: '유발 하라리',
    category: '인문',
    status: 'done',
    rating: 4.5,
    memo: '큰 흐름으로 인류사를 보는 재미가 있다.',
    startDate: '2025-08-15',
    endDate: '2025-08-26',
  },
  {
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    category: '인문',
    status: 'paused',
    rating: 3.5,
    memo: '분량이 있어 주말마다 조금씩 읽는 중.',
    startDate: '2025-09-01',
    endDate: '',
  },
  {
    title: '지적 대화를 위한 넓고 얕은 지식',
    author: '채사장',
    category: '인문',
    status: 'done',
    rating: 4,
    memo: '입문서로 여러 주제를 연결해 보기 좋다.',
    startDate: '2025-09-10',
    endDate: '2025-09-16',
  },
  {
    title: '미움받을 용기',
    author: '기시미 이치로, 고가 후미타케',
    category: '인문',
    status: 'reading',
    rating: 4,
    memo: '대화 형식이라 생각보다 잘 읽힌다.',
    startDate: '2025-09-20',
    endDate: '',
  },
  {
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    category: '인문',
    status: 'want',
    rating: 0,
    memo: '윤리적 딜레마를 토론하듯 읽어보기.',
    startDate: '',
    endDate: '',
  },
  {
    title: '클루지',
    author: '개리 마커스',
    category: '인문',
    status: 'done',
    rating: 4,
    memo: '인간 사고의 허점을 이해하는 데 도움이 됐다.',
    startDate: '2025-09-25',
    endDate: '2025-09-30',
  },
  {
    title: '논어',
    author: '공자',
    category: '고전',
    status: 'reading',
    rating: 4,
    memo: '짧은 문장을 매일 조금씩 읽기 좋다.',
    startDate: '2025-10-01',
    endDate: '',
  },
  {
    title: '명상록',
    author: '마르쿠스 아우렐리우스',
    category: '고전',
    status: 'done',
    rating: 4.5,
    memo: '차분한 자기 점검의 문장이 많다.',
    startDate: '2025-10-05',
    endDate: '2025-10-09',
  },
  {
    title: '이방인',
    author: '알베르 카뮈',
    category: '고전',
    status: 'want',
    rating: 0,
    memo: '부조리 문학을 다시 이해해보고 싶다.',
    startDate: '',
    endDate: '',
  },
  {
    title: '1984',
    author: '조지 오웰',
    category: '고전',
    status: 'done',
    rating: 5,
    memo: '지금 읽어도 날카로운 질문을 던진다.',
    startDate: '2025-10-12',
    endDate: '2025-10-18',
  },
  {
    title: '동물농장',
    author: '조지 오웰',
    category: '고전',
    status: 'done',
    rating: 4.5,
    memo: '짧고 강한 풍자의 힘이 있다.',
    startDate: '2025-10-20',
    endDate: '2025-10-22',
  },
  {
    title: '죄와 벌',
    author: '표도르 도스토옙스키',
    category: '고전',
    status: 'paused',
    rating: 3.5,
    memo: '인물 심리가 깊어 호흡을 길게 잡고 읽기.',
    startDate: '2025-10-25',
    endDate: '',
  },
  {
    title: '코스모스',
    author: '칼 세이건',
    category: '과학',
    status: 'done',
    rating: 5,
    memo: '과학적 상상력과 문장이 함께 빛난다.',
    startDate: '2025-11-01',
    endDate: '2025-11-12',
  },
  {
    title: '시간은 흐르지 않는다',
    author: '카를로 로벨리',
    category: '과학',
    status: 'reading',
    rating: 4,
    memo: '개념이 낯설지만 문장이 아름답다.',
    startDate: '2025-11-15',
    endDate: '',
  },
  {
    title: '이기적 유전자',
    author: '리처드 도킨스',
    category: '과학',
    status: 'want',
    rating: 0,
    memo: '진화론의 대표적인 관점을 제대로 읽어보기.',
    startDate: '',
    endDate: '',
  },
  {
    title: '엔트로피',
    author: '제레미 리프킨',
    category: '과학',
    status: 'paused',
    rating: 3,
    memo: '과학과 사회를 연결하는 관점이 흥미롭다.',
    startDate: '2025-11-20',
    endDate: '',
  },
  {
    title: '랩 걸',
    author: '호프 자런',
    category: '과학',
    status: 'done',
    rating: 4,
    memo: '과학자의 삶과 식물 이야기가 함께 따뜻하다.',
    startDate: '2025-11-25',
    endDate: '2025-11-30',
  },
  {
    title: '물고기는 존재하지 않는다',
    author: '룰루 밀러',
    category: '과학',
    status: 'done',
    rating: 4.5,
    memo: '분류와 혼돈을 다루는 전개가 인상적이다.',
    startDate: '2025-12-03',
    endDate: '2025-12-08',
  },
];

const seedBooks = async () => {
  try {
    // seed를 다시 실행해도 같은 50권만 남도록 기존 데이터를 비웁니다.
    await mongoose.connect(MONGO_URI);
    await Book.deleteMany({});
    await Book.insertMany(books);
    console.log(`Seed complete: ${books.length} books inserted.`);
  } catch (error) {
    console.error('Seed failed:', error.message);
    process.exitCode = 1;
  } finally {
    await mongoose.disconnect();
  }
};

seedBooks();
